### ISSUE TITLE
Epic: interface to prepare OneDep deposition

### ISSUE THREAD

**Issue by sofyalaski** [SwissOpenEM/Depositor#1]
To enable easy deposition within OneDep an infrastructure needs to be adopted. Since OneDep has no functioning API so far, we will be using a web automation tool to communicate with it. On the side of SciCat we need to adjust both frontend and backend to enable choosing of specific files from list of the archived and add extra metadata pieces. 

- [x] frontend: decide on metadata input ( exchange with David, although I expect it will be a second time user adds metadata)
- [x] decide, whether we want users to complete metadata input on scicat or in OneDep --> users should do that in OneDep
- [x] decide with Yves if extra metadata will be collected on SciCat, if It should pe a part of scientificMetadata ( maybe add another level mmCIF metadata that will contain correct key-value pairs instead?)
- [ ]  handle authentication in OneDep (#5)
- [x] Interactions with OneDep API(#6)

- [ ] backend  to choose files from the list of archived data (#3) and send it to OneDep ( retrieving to intermediate storage)
